### ISSUE TITLE
Fails to build on read-only file systems

### ISSUE THREAD

**Issue by voodooattack** [Jimdo/typings-for-css-modules-loader#36]
Using a complex docker setup, and I have my sources mounted as a read-only volume. The build fails with this error:

```
server_1    |         ERROR in ./node_modules/typings-for-css-modules-loader/lib?{"camelCase":true,"modules":true}!./node_modules/sass-loader/lib/loader.js!/site/src/pages/styles/common.scss
server_1    |         Module build failed: Error: EROFS: read-only file system, open '/site/src/pages/styles/common.scss.d.ts'
server_1    |           at Object.fs.openSync (fs.js:651:18)
server_1    |           at Object.fs.writeFileSync (fs.js:1300:33)
server_1    |           at writeFile (/dist/node_modules/typings-for-css-modules-loader/lib/persist.js:34:24)
server_1    |           at Object.writeToFileIfChanged (/dist/node_modules/typings-for-css-modules-loader/lib/persist.js:26:5)
server_1    |           at /dist/node_modules/typings-for-css-modules-loader/lib/index.js:92:15
server_1    |           at Object.<anonymous> (/dist/node_modules/css-loader/lib/localsLoader.js:44:3)
server_1    |           at /dist/node_modules/css-loader/lib/processCss.js:207:3
server_1    |           at <anonymous>:null:null
```

It would be great if there was a way to adjust the output directory for the definition files.

**Comment by timse** [comment]
not sure if that works - as typescript needs the definition files next to the scss-files to work.
At least that was last time I checked - can you verify it would work if they were somewhere else?

**Comment by voodooattack** [comment]
@timse I'm not entirely sure. Wouldn't triple slash directives work in this case though?

**Comment by timse** [comment]
i have no idea - sorry :)

**Comment by voodooattack** [comment]
@timse: Don't worry about it. I'm closing the issue now, maybe it can be revisited in the future if anyone is interested. :)
